### ISSUE TITLE
Node.js authentication with Passport.js

### ISSUE THREAD

**Issue by ruben1** [BarcelonaJS/node#12]
---
level: beginner
language: en 
twitter: ruben1
month: April

---

It's going to be about using Passport.js to implement authentication in your app. I'll talk about the basics and go through different integrations with Github or Facebook.

**Comment by PatrickHeneise** [comment]
Hey Ruben, does it work you on March 25 or rather April?

**Comment by ruben1** [comment]
Hi Patrick,

April is perfect for me. 

Thanks.

**Comment by PatrickHeneise** [comment]
I didn't read the meta data. See you in April :)

**Comment by PatrickHeneise** [comment]
This is still on for next week, right?

**Comment by ruben1** [comment]
Yes.

**Comment by ruben1** [comment]
Hey Patrick, is it possible to move it to May? I just knew I have appointment next week and not sure I'll be able to make it

**Comment by PatrickHeneise** [comment]
Ok.

**Comment by PatrickHeneise** [comment]
@ruben1 can you do the talk this Friday?

**Comment by ruben1** [comment]
Yep. Can I do 20min.?

**Comment by PatrickHeneise** [comment]
Perfect! See you Friday.

**Comment by ruben1** [comment]
Cool! See you
