### ISSUE TITLE
New Organisers

### ISSUE THREAD

**Issue by PatrickHeneise** [BarcelonaJS/node#17]
We're looking for people who want to help organise Node.js events in Barcelona - be it NodeSchool, NodeConf, talks or social events. Comment here if you're interested or have questions.

**Comment by onedesert** [comment]
I'm interested to help as much as I can. Let me know areas were help is required and I'll do my best.

**Comment by PatrickHeneise** [comment]
Awesome. We'll need help in finding speakers first and create a schedule. How about we'll have some beers soonish and talk about the details.

**Comment by onedesert** [comment]
Perfect, beers good idea.

**Comment by santihbc** [comment]
I am interested as well. I am in for the beers.

**Comment by onedesert** [comment]
When is ok for you guys the beers?

**Comment by PatrickHeneise** [comment]
25.11. or 26.11. would work for me

**Comment by onedesert** [comment]
both ok for me, although 25.10 better option for me. @santihbc @dmitry-zaets ?

**Comment by ifraixedes** [comment]
Unfortunately no way for me to make this month. Have fun!

**Comment by PatrickHeneise** [comment]
@onedesert still interested? Let's reboot this issue. @jseijas is already a co-organiser.

**Comment by onedesert** [comment]
@PatrickHeneise Yes, I am. Now I have more time. Let me know what I can help with.

**Comment by sgimeno** [comment]
@PatrickHeneise @onedesert I'm also interested in the group revive

**Comment by PatrickHeneise** [comment]
/cc @sergi 

@onedesert @sgimeno @jseijas we can meet Thursday evening to discuss responsibilities etc. and plan the event for October?

**Comment by onedesert** [comment]
for me Thursday is ok.

**Comment by PatrickHeneise** [comment]
@jseijas can't tomorrow. How about Friday?

**Comment by PatrickHeneise** [comment]
Define "early"

**Comment by sgimeno** [comment]
Friday morning is fine for me as well. We can also try a video call if meeting physically is a problem

**Comment by onedesert** [comment]
Yes, sorry I mean before 8:00 pm.

**Comment by PatrickHeneise** [comment]
That shouldn’t be an issue. How about 5pm? Works for me and Jesús

**Comment by onedesert** [comment]
ok for me I will be available until 6:30 pm, would be that ok?

**Comment by PatrickHeneise** [comment]
Works. I can also be there a bit earlier, say 4:30pm if you want.

**Comment by onedesert** [comment]
I can meet earlier as well

**Comment by onedesert** [comment]
where do we meet?

**Comment by PatrickHeneise** [comment]
BlackLab Brewery, near Barceloneta.

**Comment by onedesert** [comment]
perfect, 4:30 pm there
