### ISSUE TITLE
Should this repository be archived?

### ISSUE THREAD

**Issue by ifraixedes** [BarcelonaJS/node#19]
I'm wondering if this repo should be archived, otherwise it may be good to update the dependencies for not having the Githbu banner warning about __the potential security vulnerability__.

![image](https://user-images.githubusercontent.com/1731633/54220910-b6228200-44f2-11e9-999e-a7ddd8a8d2a1.png)

**Comment by jesus-seijas-sp** [comment]
Hello @ifraixedes , this banner must be an old one or an error... the website was removed time ago, so currently the repo has not dependencies, only the README.md

**Comment by jseijas** [comment]
Hello @ifraixedes , this banner must be an old one, and can be dismissed.
The website was removed time ago, so currently the repo has not dependencies, only the README.md
On the other hand, perhaps we should talk about what to do with the Node community

**Comment by ifraixedes** [comment]
Thanks @jseijas for your answer.

I didn't check the why, basically I get this repo in the list of the weekly email of security vulnerability on repos that I have rights.

I'm not sure what GH actually checks.

I close the issue an you may want to open a new one to talk about the Node Community.

**Comment by ifraixedes** [comment]
I found a way to dismiss the alert saying that's inappropriated, so I did so.
